package dam.hbnt.modelo;
// Generated 30 de gen. 2020, 9:57:56 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Empleados generated by hbm2java
 */
public class Empleados  implements java.io.Serializable {


     private short empNo;
     private String apellido;
     private String oficio;
     private Short dir;
     private Date fechaAlt;
     private Float salario;
     private Float comision;
     private byte deptNo;

    public Empleados() {
    }

	
    public Empleados(short empNo, byte deptNo) {
        this.empNo = empNo;
        this.deptNo = deptNo;
    }
    public Empleados(short empNo, String apellido, String oficio, Short dir, Date fechaAlt, Float salario, Float comision, byte deptNo) {
       this.empNo = empNo;
       this.apellido = apellido;
       this.oficio = oficio;
       this.dir = dir;
       this.fechaAlt = fechaAlt;
       this.salario = salario;
       this.comision = comision;
       this.deptNo = deptNo;
    }
   
    public short getEmpNo() {
        return this.empNo;
    }
    
    public void setEmpNo(short empNo) {
        this.empNo = empNo;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getOficio() {
        return this.oficio;
    }
    
    public void setOficio(String oficio) {
        this.oficio = oficio;
    }
    public Short getDir() {
        return this.dir;
    }
    
    public void setDir(Short dir) {
        this.dir = dir;
    }
    public Date getFechaAlt() {
        return this.fechaAlt;
    }
    
    public void setFechaAlt(Date fechaAlt) {
        this.fechaAlt = fechaAlt;
    }
    public Float getSalario() {
        return this.salario;
    }
    
    public void setSalario(Float salario) {
        this.salario = salario;
    }
    public Float getComision() {
        return this.comision;
    }
    
    public void setComision(Float comision) {
        this.comision = comision;
    }
    public byte getDeptNo() {
        return this.deptNo;
    }
    
    public void setDeptNo(byte deptNo) {
        this.deptNo = deptNo;
    }

    @Override
    public String toString() {
        return "Empleado: ["+ this.getDeptNo();
    }
    
    


}


